version: '3.7'

services:
  apache:
    image: httpd
    ports:
      - "81:80"
  nginx:
    image: nginx
    ports:
      - "82:80"
  web:
    build: .
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/todo_backend_dev
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - my-network
  test:
    build: .
    command: mix test
    environment:
      - MIX_ENV=test
      - DATABASE_URL=ecto://postgres:postgres@postgres/todo_backend_test
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge