version: '3.7'

services:
  apache:
    image: httpd
    ports:
      - "81:80"
  nginx:
    image: nginx
    ports:
      - "82:80"
  web:
    image: docker.io/geegog/docker-phoenix
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@localhost/todo_backend_dev
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    network_mode: "host"

  postgres:
    image: postgres:latest
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"